version: "3.3"

services:
  app:
    build:
      context: .
    image: forgetful
    ports:
      - 80:3000
    environment:
      - MONGO_URI=mongodb://mongo_db/forgetfulDEV
    networks:
      - nodegraphqlapp
  db:
    image: mongo:3.0.15
    volumes:
      - mongo-db:/data/db
    networks:
      nodegraphqlapp:
        aliases:
          - "mongo_db"

volumes:
  mongo-db:

networks:
  nodemernapp:
    driver: bridge
